version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@6.7.0

jobs:
  create-pull-request:
    docker:
      - image: circleci/python:3.7.4-stretch
    steps:
      - checkout
      - run:
          name: install hub
          command: |
            curl -sSLf https://github.com/github/hub/releases/download/v2.8.3/hub-linux-amd64-2.8.3.tgz | \
            tar zxf - --strip-components=1 -C /tmp/ && \
            sudo mv /tmp/bin/hub /usr/local/bin/hub
            hub --version
      - run:
          name: install yq
          command: |
            sudo pip install --upgrade pip
            sudo pip install yq
      - run:
          name: git clone commit push create pull request
          command: |
            git config --global user.name ${GITHUB_NAME}
            git config --global user.email ${GITHUB_EMAIL}
            # TODO add git repo
            git clone https://${GITHUB_NAME}:${GITHUB_TOKEN}@github.com/yuzujoe/manifest-gitops.git
            cd manifest-gitops
            git init
            git checkout -b update-image-${CIRCLE_SHA1}
            yq -y -i '.images |= map(select(.name=="XXXXXXXXXXXX.dkr.ecr.ap-northeast-1.amazonaws.com/sample").newTag |= "'$CIRCLE_SHA1'")' k8s/overlays/dev/bases/kustomization.yaml
            git add .
            git commit -m "update-image-${CIRCLE_SHA1}"
            git push --set-upstream origin update-image-${CIRCLE_SHA1}
            hub pull-request -m "[image update] application ${CIRCLE_SHA1}"

workflows:
  build_and_push_image:
      jobs:
        - aws-ecr/build-and-push-image:
            # XXXXXXXXXXX.dkr.ecr.<YOUR REGION>.amazonaws.com
            account-url: AWS_ECR_ACCOUNT_URL
            aws-access-key-id: AWS_ACCESS_KEY_ID
            aws-secret-access-key: AWS_SECRET_ACCESS_KEY
            region: AWS_DEFAULT_REGION
            repo: '${MY_APP_PREFIX}'
            tag: '${CIRCLE_SHA1}'
            path: ./
            filters:
              branches:
                only:
                  - master
        - create-pull-request:
            filters:
              branches:
                only:
                  - master
